"""
Date: 11/04/2021
Author: David Greybosh

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

def check_even(n: int):
    if n % 2 == 0: return True
    else: return False

def find_fibonacci(value: int):
    numbers = [0, 1]
    while numbers[-1] < value:
        numbers.append(numbers[-1] + numbers[-2])
    return numbers

def main():
    full_sum = sum(filter(check_even, find_fibonacci(4000000)))
    print(full_sum)

if __name__ == '__main__':
    main()
